# Generated by Django 5.1.7 on 2025-03-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('subject', models.CharField(max_length=150, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение с сайта',
                'verbose_name_plural': 'Сообщения с сайта',
            },
        ),
        migrations.AlterField(
            model_name='trackinfo',
            name='shipment_departure_time',
            field=models.DateTimeField(help_text='Дата отправки груза из страны отправителя', verbose_name='Дата отправки груза'),
        ),
        migrations.AlterField(
            model_name='trackinfo',
            name='shipment_enter_uzb',
            field=models.DateTimeField(help_text='Дата прилета в страну назначения', verbose_name='Дата прилета'),
        ),
        migrations.AlterField(
            model_name='trackinfo',
            name='shipment_process_local',
            field=models.DateTimeField(help_text='Когда посылка была принята на склад', verbose_name='Дата принятия на склад'),
        ),
        migrations.AlterField(
            model_name='trackinfo',
            name='shipment_received_time',
            field=models.DateTimeField(help_text='Дата доставки посылки получателю', verbose_name='Дата доставки'),
        ),
    ]
