# Generated by Django 5.1.7 on 2025-03-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_requestmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
