# Generated by Django 5.1.7 on 2025-03-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_requestmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinfo',
            name='shipment_departure_time',
            field=models.DateField(help_text='Дата отправки груза из страны отправителя', verbose_name='Дата отправки груза'),
        ),
        migrations.AlterField(
            model_name='trackinfo',
            name='shipment_enter_uzb',
            field=models.DateField(help_text='Дата прилета в страну назначения', verbose_name='Дата прилета'),
        ),
        migrations.AlterField(
            model_name='trackinfo',
            name='shipment_id_create_time',
            field=models.DateField(help_text='Когда сформирован заказ на складе отправителя', verbose_name='Дата формирования заказа'),
        ),
        migrations.AlterField(
            model_name='trackinfo',
            name='shipment_process_local',
            field=models.DateField(help_text='Когда посылка была принята на склад', verbose_name='Дата принятия на склад'),
        ),
        migrations.AlterField(
            model_name='trackinfo',
            name='shipment_received_time',
            field=models.DateField(help_text='Дата доставки посылки получателю', verbose_name='Дата доставки'),
        ),
    ]
