# Generated by Django 5.1.7 on 2025-03-17 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_trackinfo_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinfo',
            name='correlation_id',
            field=models.UUIDField(default=uuid.UUID('3ae579de-f8af-43d6-9b23-f6b41a3737dc')),
        ),
    ]
