# Generated by Django 5.1.7 on 2025-03-17 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_trackinfo_correlation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinfo',
            name='correlation_id',
            field=models.UUIDField(default=uuid.UUID('9f60f1b8-0718-4ce3-af98-74083f3f1324')),
        ),
    ]
