# Generated by Django 5.1.7 on 2025-03-18 09:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_trackinfo_correlation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinfo',
            name='correlation_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
