# Generated by Django 5.1.7 on 2025-03-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_trackinfo_correlation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinfo',
            name='county_name',
            field=models.CharField(default='Корея', max_length=60, verbose_name='Название страны отправителя'),
        ),
    ]
