# Generated by Django 5.1.7 on 2025-03-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_trackinfo_county_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinfo',
            name='status',
            field=models.CharField(choices=[(None, ''), ('Доставляется', 'Delivering'), ('Доставлено', 'Delivered'), ('На складе', 'On Warehouse')], default='Доставляется', max_length=20, verbose_name='Статус доставки'),
        ),
    ]
